// home
export const GROUPBUYING_POST_HOME = 'GROUPBUYING_POST_HOME'

// product
export const PRODUCT_GET = 'PRODUCT_GET'

// preorder
export const PREORDER_POST = 'PREORDER_POST'
export const PREORDER_POST_ADDRESS = 'PREORDER_POST_ADDRESS'

// product-collection 收藏
export const PRODUCTCEOLLECTION_POST_ADD = 'PRODUCTCEOLLECTION_POST_ADD'
export const PRODUCTCEOLLECTION_DEL_REMOVE = 'PRODUCTCEOLLECTION_DEL_REMOVE'
export const PRODUCTCEOLLECTION_POST_LOADMORE = 'PRODUCTCEOLLECTION_POST_LOADMORE'
export const PRODUCTCEOLLECTION_DEL_CLEARALL = 'PRODUCTCEOLLECTION_DEL_CLEARALL'

// order
export const USER__ORDER_GETS = 'USER__ORDER_GETS'
export const USER__ORDER_POST_CLEARITEMTAB = 'USER__ORDER_POST_CLEARITEMTAB'

// groupon
export const ONGROUPON_POST_HOME = 'ONGROUPON_POST_HOME'

// nav
export const NAV_SET_INDEX = 'NAV_SET_INDEX'

// user
export const USER_GET = 'USER_GET'
export const USER_SET = 'USER_SET'
